In [1]:
import numpy as np
import xarray as xr

In [10]:
da = xr.DataArray(np.arange(9).reshape(1,3,3),
             coords=[('outer', np.array([(1, 10),], dtype=[('v1', 'f8'), ('v2', 'f8')])),
                     ('inner 1', np.arange(3)), 
                     ('inner 2', np.arange(3,6))])

In [11]:
da

<xarray.DataArray (outer: 1, inner 1: 3, inner 2: 3)>
array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])
Coordinates:
  * outer    (outer) [('v1', '<f8'), ('v2', '<f8')] ( 1.,  10.)
  * inner 1  (inner 1) int32 0 1 2
  * inner 2  (inner 2) int32 3 4 5

In [12]:
db = xr.DataArray([0.001,],
             coords=[('outer', np.array([(1, 10),], dtype=[('v1', 'f8'), ('v2', 'f8')])),]) 

In [13]:
db

<xarray.DataArray (outer: 1)>
array([ 0.001])
Coordinates:
  * outer    (outer) [('v1', '<f8'), ('v2', '<f8')] ( 1.,  10.)

In [14]:
ds = xr.Dataset({'complex_data' : da, 'simple_data' : db})

In [15]:
ds

<xarray.Dataset>
Dimensions:       (inner 1: 3, inner 2: 3, outer: 1)
Coordinates:
  * outer         (outer) [('v1', '<f8'), ('v2', '<f8')] ( 1.,  10.)
  * inner 1       (inner 1) int32 0 1 2
  * inner 2       (inner 2) int32 3 4 5
Data variables:
    complex_data  (outer, inner 1, inner 2) int32 0 1 2 3 4 5 6 7 8
    simple_data   (outer) float64 0.001

In [16]:
ds.to_netcdf('test.hdf5', format='NETCDF4')

ValueError: cannot infer dtype for netCDF4 variable

In [17]:
da = xr.DataArray(np.arange(9).reshape(1,3,3),
             coords=[('outer', [1,]),
                     ('inner 1', np.arange(3)), 
                     ('inner 2', np.arange(3,6))])

In [18]:
da

<xarray.DataArray (outer: 1, inner 1: 3, inner 2: 3)>
array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])
Coordinates:
  * outer    (outer) int32 1
  * inner 1  (inner 1) int32 0 1 2
  * inner 2  (inner 2) int32 3 4 5

In [19]:
db = xr.DataArray([0.001,],
             coords=[('outer', [1,])]) 

In [20]:
db

<xarray.DataArray (outer: 1)>
array([ 0.001])
Coordinates:
  * outer    (outer) int32 1

In [21]:
ds = xr.Dataset({'complex_data' : da, 'simple_data' : db})

In [22]:
ds

<xarray.Dataset>
Dimensions:       (inner 1: 3, inner 2: 3, outer: 1)
Coordinates:
  * outer         (outer) int32 1
  * inner 1       (inner 1) int32 0 1 2
  * inner 2       (inner 2) int32 3 4 5
Data variables:
    complex_data  (outer, inner 1, inner 2) int32 0 1 2 3 4 5 6 7 8
    simple_data   (outer) float64 0.001

In [23]:
ds.to_netcdf('test.hdf5', format='NETCDF4')